### ISSUE TITLE
Bug Report | Netty exception

### ISSUE THREAD

**Issue by GhostAndry** [micartey/Cardinal-Anticheat#165]
```
[21:36:58 ERROR]: Could not pass event PlayerTeleportEvent to Cardinal v1.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[hub.jar:]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[hub.jar:]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[hub.jar:]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[hub.jar:]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[hub.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:622) ~[hub.jar:]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:408) ~[hub.jar:]
        at me.clientastisch.checks.b.a(Unknown Source) ~[?:?]
        at me.clientastisch.aZ.a(Unknown Source) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.clientastisch.events.EventManager.a(Unknown Source) ~[?:?]
        at me.clientastisch.events.EventManager.b(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.channel.ChannelHandlerContext.writeAndFlush(Object)" because the return value of "io.netty.channel.ChannelPipeline.context(String)" is null
        at me.clientastisch.cardinal.dependencies.packetevents.io.netty.channel.ChannelOperatorModernImpl.writeAndFlushInContext(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.dependencies.packetevents.netty.channel.ChannelHelper.writeAndFlushInContext(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.dependencies.packetevents.io.manager.protocol.ProtocolManagerImpl.sendPacketSilently(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.dependencies.packetevents.manager.protocol.ProtocolManager.sendPacketsSilently(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.dependencies.packetevents.manager.protocol.ProtocolManager.sendPacketSilently(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.dependencies.packetevents.manager.player.PlayerManager.sendPacketSilently(Unknown Source) ~[?:?]
        at me.clientastisch.J.a(Unknown Source) ~[?:?]
        at me.clientastisch.r.a(Unknown Source) ~[?:?]
        at me.clientastisch.controller.f.a(Unknown Source) ~[?:?]
        at me.clientastisch.events.bukkit.BukkitTeleportEvent.onTeleport(Unknown Source) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[hub.jar:]
        ... 16 more

```

Cardinal Version: Latest

Spigot Version: 1.8.8 WindSpigot

> **Attached Files  (Required)**

**Comment by micartey** [comment]
Does this issue only happen when using `WindSpigot` ?

**Comment by micartey** [comment]
I suspect it happens due to the used netty version in that fork/build

**Comment by GhostAndry** [comment]
no it happend with every spigot

**Comment by micartey** [comment]
What spigots did you try for 1.8.8?
- [ ] Paper
- [ ] Spigot
- [x] WindSpigot

**Comment by GhostAndry** [comment]
On every spigot fork and original

**Comment by micartey** [comment]
Minecraft version 1.8 ?

**Comment by GhostAndry** [comment]
> Minecraft version 1.8 ?

Yes

**Comment by micartey** [comment]
What Java version are you running?
