### ISSUE TITLE
Bug Report | Startup Exception

### ISSUE THREAD

**Issue by HackHsda** [micartey/Cardinal-Anticheat#174]
What type of bug you want to report? Describe it here
[21:16:11 INFO]: [Cardinal] Enabling Cardinal v1.0.0
[21:16:12 INFO]:

                           .o88b.  .d8b.   .o88b.
                          d8P  Y8 d8' `8b d8P  Y8
                          8P      88ooo88 8P
                          8b      88   88 8b
                          Y8b  d8 88   88 Y8b  d8
                           `Y88P' YP   YP  `Y88P'

 _              _____ _ _            _            _   _          _
| |            / ____| (_)          | |          | | (_)        | |
| |__  _   _  | |    | |_  ___ _ __ | |_ __ _ ___| |_ _ ___  ___| |__
| '_ \| | | | | |    | | |/ _ \ '_ \| __/ _` / __| __| / __|/ __| '_ \
| |_) | |_| | | |____| | |  __/ | | | || (_| \__ \ |_| \__ \ (__| | | |
|_.__/ \__, |  \_____|_|_|\___|_| |_|\__\__,_|___/\__|_|___/\___|_| |_|
        __/ |
       |___/

[21:16:12 INFO]: Detected server version VERSION_1_8

[21:16:12 INFO]: Loaded Checks: 111

[21:16:12 WARN]: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

[21:16:12 WARN]: SLF4J: Defaulting to no-operation (NOP) logger implementation

[21:16:12 WARN]: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

[21:16:12 ERROR]: Error occurred while enabling Cardinal v1.0.0 (Is it up to date?)
java.lang.ExceptionInInitializerError
        at me.clientastisch.core.Plugin.printInfo(Native Method) ~[?:?]
        at me.clientastisch.core.Core.init(Native Method) ~[?:?]
        at me.clientastisch.core.Plugin.onEnable(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.core.Core.onEnable(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274) ~[?:?]
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188) ~[?:?]
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177) ~[?:?]
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:162) ~[?:?]
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329) ~[?:?]
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396) ~[?:?]
        at java.base/java.nio.file.Files.readAllLines(Files.java:3415) ~[?:?]
        at me.clientastisch.m.a(Unknown Source) ~[?:?]
        at me.clientastisch.k.a(Unknown Source) ~[?:?]
        at me.clientastisch.k$1.a(Unknown Source) ~[?:?]
        at me.clientastisch.I.a(Native Method) ~[?:?]
        at me.clientastisch.I.$nativeClinit(Native Method) ~[?:?]
        at me.clientastisch.I.<clinit>(Unknown Source) ~[?:?]
        ... 15 more

When does the bug occurr?

Cardinal Version:
GitHub
Spigot Version:
1.8.9

> **Attached Files  (Required)**

**Comment by micartey** [comment]
Should be fixed in the 4.0 branch. If the issue persists, please consider reopening the issue and provide logs in file format.
