### ISSUE TITLE
Bug Report | Illegal modifiers: 0x101

### ISSUE THREAD

**Issue by Happies123** [micartey/Cardinal-Anticheat#183]
### Information

Load error

### When does the bug occure?

[18:03:07 ERROR]: Could not load 'plugins\Cardinal-final.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Method <init> in class me/clientastisch/cardinal/lllIlIlllIlIlIIlIlIl has illegal modifiers: 0x101
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_391]
Caused by: java.lang.ClassFormatError: Method <init> in class me/clientastisch/cardinal/lllIlIlllIlIlIIlIlIl has illegal modifiers: 0x101
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_391]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_391]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_391]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_391]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_391]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_391]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_391]
        at me.clientastisch.cardinal.loader.core.Core.<init>(Unknown Source) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_391]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_391]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_391]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_391]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_391]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 6 more

### Cardinal Version

4.0.0-alpha.4

### Spigot Version

1.8.9

### Additional information

China network

**Comment by micartey** [comment]
Can you upload the whole log?
It might be possible that there is additional information that is currently not visible.

> ... 6 more

**Comment by Happies123** [comment]
logs file
![图片](https://github.com/micartey/Cardinal-Anticheat/assets/154600472/3d130f80-7b22-4fa8-9f71-934380b94e7d)

**Comment by micartey** [comment]
This is but a screenshot, but whatever...

Please answer the following questions first
- [ ] What java version and vendor are you using?
- [ ] Do you use a Security Manager?

**Comment by Happies123** [comment]
Java17 no use

**Comment by micartey** [comment]
What vendor?

**Comment by Happies123** [comment]
Can you speak Chinese、？？？

**Comment by Happies123** [comment]
Bro I find error!

**Comment by micartey** [comment]
> Can you speak Chinese、？？？

No

**Comment by Happies123** [comment]
Dont use slimeworldmanager-classmodifier-2.2.1!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11

**Comment by Happies123** [comment]
[19:44:29 INFO]: CAC: Using branch stable
[19:44:39 INFO]: Failed load library:C:\Users\Administrator\AppData\Local\Temp\lib8252913206787115456.tmp
[19:44:39 WARN]: java.lang.UnsatisfiedLinkError: C:\Users\Administrator\AppData\Local\Temp\lib8252913206787115456.tmp: %1 涓嶆槸鏈夋晥鐨?Win32 搴旂敤绋嬪簭銆?

[19:44:39 WARN]:        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
[19:44:39 WARN]:        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
[19:44:39 WARN]:        at java.lang.ClassLoader.loadLibrary(Unknown Source)
[19:44:39 WARN]:        at java.lang.Runtime.load0(Unknown Source)
[19:44:39 WARN]:        at java.lang.System.load(Unknown Source)
[19:44:39 WARN]:        at me.clientastisch.cardinal.native.NativeLoader.<clinit>(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[19:44:39 WARN]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
[19:44:39 WARN]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
[19:44:39 WARN]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
[19:44:39 WARN]:                                                           )
[19:44:39 WARN]:        at me.clientastisch.cardinal.core.Plugin.<clinit>(Unknown Source)
[19:44:39 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:44:39 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:44:39 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:44:39 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:44:39 WARN]:        at me.clientastisch.cardinal.IlllllllIlIlIlIIllIl.lllIlIlllIlIlIIlIlIl(Unknown Source)
[19:44:39 WARN]:        at me.clientastisch.cardinal.lllIlIlllIlIlIIlIlIl.lllIlIlllIlIlIIlIlIl(Unknown Source)
[19:44:39 WARN]:        at me.clientastisch.cardinal.loader.core.Core.<init>(Unknown Source)
[19:44:39 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:44:39 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:44:39 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:44:39 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:44:39 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[19:44:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77)
[19:44:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129)
[19:44:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331)
[19:44:39 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254)
[19:44:39 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293)
[19:44:39 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202)
[19:44:39 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
[19:44:39 WARN]:        at java.lang.Thread.run(Unknown Source)
[19:44:39 ERROR]: Could not load 'plugins\Cardinal-final.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsatisfiedLinkError: me.clientastisch.cardinal.core.Plugin.$nativeLoader()V
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:331) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:254) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:202) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_391]
Caused by: java.lang.UnsatisfiedLinkError: me.clientastisch.cardinal.core.Plugin.$nativeLoader()V
        at me.clientastisch.cardinal.core.Plugin.$nativeLoader(Native Method) ~[?:?]
        at me.clientastisch.cardinal.core.Plugin.<clinit>(Unknown Source) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_391]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_391]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_391]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_391]
        at me.clientastisch.cardinal.IlllllllIlIlIlIIllIl.lllIlIlllIlIlIIlIlIl(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.lllIlIlllIlIlIIlIlIl.lllIlIlllIlIlIIlIlIl(Unknown Source) ~[?:?]
        at me.clientastisch.cardinal.loader.core.Core.<init>(Unknown Source) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_391]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_391]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_391]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_391]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_391]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:77) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 6 more
error again....

**Comment by micartey** [comment]
> Win32

🤔 

Are you not using a 64-bit system?

**Comment by Happies123** [comment]
I am using 64-bit Windons10

**Comment by Happies123** [comment]
![图片](https://github.com/micartey/Cardinal-Anticheat/assets/154600472/612fc4a5-2e86-4e74-80b9-fb4c73a9eacb)

**Comment by micartey** [comment]
Can you test it on a linux machine?
I, personally, don't have windows and no issues on Linux

**Comment by Happies123** [comment]
OK I have a linux server pls wait

**Comment by Happies123** [comment]
![图片](https://github.com/micartey/Cardinal-Anticheat/assets/154600472/431a0aed-23ec-4540-8e47-9d2c288f807c)
Linux and use your AntiCheat error

**Comment by micartey** [comment]
At least some progress - another error.
Although this one is even worse 💀

**Comment by micartey** [comment]
Issue is being closed due to inactivity.
Please open a new issue if the issue persist.
