### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by bbb908** [micartey/Cardinal-Anticheat#187]
### Information

Immediate server crash

### When does the bug occure?

On the server starting

### Cardinal Version

4

### Spigot Version

1.18.2

### Additional information

Console output:

[18:41:22 INFO]: [STDOUT] [me.micartey.jcloak.IIllIlllIllIIIlllllI] sun.misc.Unsafe
[18:41:22 INFO]: CAC: Using branch stable 
[18:41:23 INFO]: Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
2024-02-15 18:41:23,631 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
	at java.base/java.lang.Thread.stop(Thread.java:942)
	at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:960)
	at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:803)
	at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:932)
	at org.bukkit.craftbukkit.v1_18_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:28)
[18:41:23 ERROR]: Exception stopping the server
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:942) ~[?:?]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:960) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:932) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[paper-1.18.2.jar:git-Paper-388]

**Comment by micartey** [comment]
Version 4.1 will allow the Unsafe class
